version: '3.9'

services:
  test:
    image: 'java-api:latest'
    ports:
      - "8080:8080"
    build:
      context: .
    container_name: test
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stefanvacareanu
      - SPRING_DATASOURCE_USERNAME=stefanvacareanu
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.4'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=stefanvacareanu
      - POSTGRES_HOST_AUTH_METHOD=trust